### ISSUE TITLE
Configurar database do firebase

### ISSUE THREAD

**Issue by GabrielGaba** [terzeu/invites-website#60]
- Configurar database do firebase para cadastrar os convidados.

**Comment by terzeu** [comment]
A tabela guests deve conter os seguintes campos:
- name: nome do convidado, que aparecerá na lista no site
- group: identificador da família do convidado
- presence: booleano -> false = presença nao confirmada, true -> presença confirmada. Todos convidados começam false
- confirmedDate: tipo timestamp que gravará quando o convidado confirmou presença
- lastPreviewInvite: tipo timestamp que gravará a ultima vez que o convidado abriu o site

**Comment by terzeu** [comment]
https://www.base64encode.org/
